kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
data:
  "KubeServerUrl": QWRkWW91clNlY3JldA==
  "KubeAccessToken": QWRkWW91clNlY3JldA==
  "KubeUserName": QWRkWW91clNlY3JldA==
  "KubePassWord": QWRkWW91clNlY3JldA==

