kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
data:
  "KubernetesSetting:ServerUrl": QWRkWW91clNlY3JldA==
  "KubernetesSetting:AccessToken": QWRkWW91clNlY3JldA==
  "KubernetesSetting:UserName": QWRkWW91clNlY3JldA==
  "KubernetesSetting:PassWord": QWRkWW91clNlY3JldA==

